### ISSUE TITLE
POST /api/run_sse rejects functionCallEventId field sent by adk-web dev-ui

### ISSUE THREAD

**Issue by st699pic** [google/adk-go#941]
## Bug Description

When using the ADK dev-ui (adk-web) to respond to a long-running function call (e.g., OAuth authorization or human-in-the-loop confirmation), the request to `POST /api/run_sse` fails with:

```
failed to decode request body: failed to decode request: json: unknown field "functionCallEventId"
```

## Root Cause

The dev-ui frontend (bundled in `cmd/launcher/web/webui/distr/main-*.js`) sends `functionCallEventId` in the request body when resuming a long-running function call:

```javascript
// From dev-ui bundle (minified)
let e = {
  appName: this.appName,
  userId: this.userId,
  sessionId: this.sessionId,
  newMessage: { role: "user", parts: [{ functionResponse: {...} }] },
  functionCallEventId: this.functionCall.functionCallEventId  // ← this field
};
this.agentService.runSse(e).subscribe(...)
```

However, the Go backend `RunAgentRequest` struct (`server/adkrest/internal/models/runtime.go:23`) does not define this field:

```go
type RunAgentRequest struct {
    AppName    string          `json:"appName"`
    UserId     string          `json:"userId"`
    SessionId  string          `json:"sessionId"`
    NewMessage genai.Content   `json:"newMessage"`
    Streaming  bool            `json:"streaming,omitempty"`
    StateDelta *map[string]any `json:"stateDelta,omitempty"`
}
```

And the decoder at `server/adkrest/controllers/runtime.go:240` uses `DisallowUnknownFields()`:

```go
func decodeRequestBody(req *http.Request) (models.RunAgentRequest, error) {
    var runAgentRequest models.RunAgentRequest
    d := json.NewDecoder(req.Body)
    d.DisallowUnknownFields()  // ← rejects functionCallEventId
    ...
}
```

## Expected Behavior

The `/run_sse` endpoint should accept the `functionCallEventId` field (either by adding it to the struct or by removing strict unknown-field validation), allowing the dev-ui long-running function call flow to work end-to-end.

## Steps to Reproduce

1. Configure an agent with a long-running tool (e.g., one requiring user confirmation or OAuth)
2. Start the agent with `adk web` or using `full.NewLauncher()`
3. Send a message that triggers the long-running tool
4. In the dev-ui, respond to the function call confirmation dialog
5. Observe the 400 error: `json: unknown field "functionCallEventId"`

## Environment

- ADK Go version: v1.4.0 (latest)
- Dev-UI: bundled version in `cmd/launcher/web/webui/distr/`

## Suggested Fix

Add `FunctionCallEventId` to the `RunAgentRequest` struct:

```go
type RunAgentRequest struct {
    AppName             string          `json:"appName"`
    UserId              string          `json:"userId"`
    SessionId           string          `json:"sessionId"`
    NewMessage          genai.Content   `json:"newMessage"`
    Streaming           bool            `json:"streaming,omitempty"`
    StateDelta          *map[string]any `json:"stateDelta,omitempty"`
    FunctionCallEventId string          `json:"functionCallEventId,omitempty"`
}
```

**Comment by indurireddy-TF** [comment]
Hi @st699pic I have successfully reproduced this bug locally using `v1.4.0` with a tool requiring human confirmation (`RequireConfirmation: true`). 

Upon clicking the **Confirm** button in the Dev-UI, the subsequent `POST` request to `/api/run_sse` fails with a `400 Bad Request` and the error:
`failed to decode request body: failed to decode request: json: unknown field "functionCallEventId"`

This is indeed a valid bug caused by the backend's strict JSON decoding configuration (`DisallowUnknownFields()`) rejecting the `functionCallEventId` sent by the frontend, which is missing from the `RunAgentRequest` struct in `server/adkrest/internal/models/runtime.go`.

<img width="2932" height="1282" alt="Image" src="https://github.com/user-attachments/assets/e4162364-737d-40e3-b8cb-b6c58d23da91" />

**Comment by indurireddy-TF** [comment]
Applied the proposed fix locally by adding the `FunctionCallEventId` field to the `RunAgentRequest` struct in `server/adkrest/internal/models/runtime.go`:

After rebuilding and running the agent with this change, the manual confirmation flow completes successfully. The backend decodes the payload, executes the tool, and successfully returns the response to the Dev-UI without throwing the 400 error.

<img width="2934" height="1300" alt="Image" src="https://github.com/user-attachments/assets/5aac77a9-c246-412d-ab8f-3de798238ae6" />

**Comment by pallat** [comment]
Confirming this on `v1.4.0` — independently reproduced while building a
teaching example. All three confirmation styles are affected
(`RequireConfirmation: true`, `RequireConfirmationProvider`, and manual
`ctx.RequestConfirmation()`), since they all surface the same
`adk_request_confirmation` long-running call.

Root cause matches the report: the bundled web UI POSTs `functionCallEventId`
in the `/api/run_sse` body, but `RunAgentRequest`
(`server/adkrest/internal/models/runtime.go`) has no such field, and the
controller decodes with `DisallowUnknownFields()`
(`server/adkrest/controllers/runtime.go:239-241`) → HTTP 400, so the confirmed
tool never runs.

Minimal repro via curl:

```bash
# WITHOUT functionCallEventId → 200, tool runs
curl -s -X POST localhost:8080/api/run -H 'Content-Type: application/json' -d '{
  "appName":"A","userId":"user","sessionId":"S",
  "newMessage":{"role":"user","parts":[{"functionResponse":{
    "id":"<adk_request_confirmation id>","name":"adk_request_confirmation",
    "response":{"confirmed":true}}}]}}'

# WITH functionCallEventId (what the UI sends) → 400
#   json: unknown field "functionCallEventId"

Workaround for anyone blocked until #977 lands: send the confirmation via
/api/run without functionCallEventId (look up the pending
adk_request_confirmation id from the session, POST {"confirmed": true|false}).

**Comment by vhuk2025** [comment]
Why hasn't the PR been approved yet

**Comment by kdroste-google** [comment]
After the migration to v2 it seems to be fine:

`go run ./examples/workflow/hitl_simple/main.go  web webui api`

Produces:
```json
{
    "appName": "hitl_simple",
    "userId": "user",
    "sessionId": "99999999-9999-9999-9999-999999999999",
    "newMessage": {
        "role": "user",
        "parts": [
            {
                "functionResponse": {
                    "id": "ask_name-99999999-9999-9999-9999-999999999999",
                    "name": "adk_request_input",
                    "response": {
                        "result": "name"
                    }
                }
            }
        ]
    },
    "streaming": false,
    "stateDelta": null,
    "functionCallEventId": "99999999-9999-9999-9999-999999999999"
}
```

Which is accepted by the run_sse. 
@st699pic Could you confirm?

**Comment by indurireddy-TF** [comment]
Hi @st699pic Closing this issue as the fix has been implemented and released in the v2.0.0 version. Thanks!
